[package]
name = "ynab-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "JSON-first command line client for YNAB"

[[bin]]
name = "ynab-cli"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
clap.workspace = true
comfy-table.workspace = true
keyring.workspace = true
miette.workspace = true
rust_decimal.workspace = true
rpassword = "7.3.1"
secrecy.workspace = true
serde.workspace = true
serde_json.workspace = true
time.workspace = true
tokio.workspace = true
uuid.workspace = true
ynab-sdk = { path = "../ynab-sdk", version = "0.1.0" }


[dev-dependencies]
assert_cmd = "2.0.16"
url.workspace = true
wiremock = "=0.6.5"
